name: Kotlin CI with Gradle for master

on:
  push:
    branches: [ master ]
    paths-ignore:
      - README.md
      - .gitignore
      - docs/**
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Test with Gradle
        run: ./gradlew test

  generate-docs:
    runs-on: ubuntu-latest
    needs: [ test ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Generate html docs with dokka
        run: ./gradlew dokkaHtml
      - name: Push generated html docs to github
        run:  |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add docs
          git commit -m "Update docs: ${{ github.event.head_commit.message }}"
          git push
