name: Kotlin CI with Gradle for master

on:
  push:
    branches: [ master ]
    paths-ignore:
      - README.md
      - .gitignore
      - docs/**
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build -x test

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Test with Gradle
        run: ./gradlew test

  generate-docs:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Generate gfm docs with dokka
        run: ./gradlew dokkaGfm
      - name: Push generated gfm docs to github
        run:  |
          git config --global user.name "Janghyub Seo"
          git config --global user.email "seojanghyeob@gmail.com"

          git add docs
          git commit -m "Update docs"
          git push